### ISSUE TITLE
tip: check/remove FOSSGIS provider to ensure queries go to localhost

### ISSUE THREAD

**Issue by stevegt** [gis-ops/valhalla-qgis-plugin#10]
(@nilsnolde feel free to close -- I'm adding this here to help anyone else who runs into the same problem and does a search.)

If anyone runs into a problem where you're using a localhost valhalla instance but finding entries in valhalla.json seeming to be ignored, try deleting the FOSSGIS entry in `Web | Valhalla | Provider Settings`.  In my own case, I found isochrones were limited to 100 minutes even though I had max_time_contour set to 300 in valhalla.json.  

It turns out that, even though I had localhost selected as the provider in `Web | Valhalla | Valhalla | Provider`, the queries were still going to FOSSGIS.  The clue I should have seen was the .de URL in `Web | Valhalla | Valhalla | Log`.  

It didn't seem to matter how I had `Web | Valhalla | Valhalla | Provider` set.  When I completely deleted the FOSSGIS provider the problem went away.  

I wasn't able to duplicate the problem afterward:  When I added FOSSGIS back as a provider the problem did not return, regardless of whether FOSSGIS was the first or second provider in the list.  It's worth noting that this odd behavior had persisted over multiple executions of QGIS, so whatever was causing it was also persisted on disk.

QGIS Valhalla plugin version 2.4.1.

**Comment by nilsnolde** [comment]
I'm using this constantly since years for debugging and never fails to work switching URLs. Guessing it was some hiccup on your system for some reason:)
