### ISSUE TITLE
Mapbox host issues

### ISSUE THREAD

**Issue by atimpabi** [gis-ops/valhalla-qgis-plugin#11]
Please I am running Valhalla in qgis on a Mapbox api. I have been using this for a while until lately these feedbacks appear without any isochrones outputs: 

ApiError:
403 (Error transferring https://api.mapbox.com/valhalla/v1/isochrone?access_token=pk.eyJ1Ijoia3V1NDciLCJhIjoiY2xqNHRzZ2QxMDYwdjNwcXk1czdoZndpayJ9.Q5E9b2gS8CGk--Q8AdR_Hw - server replied: Forbidden)
Was caused by feature ID 30 with parameters {'polygons': True, 'contours': [{'time': 6.0}, {'time': 15.0}, {'time': 30.0}, {'time': 60.0}], 'costing': 'bicycle', 'show_locations': True, 'locations': [{'lon': -0.780077, 'lat': 9.43348}], 'costing_options': {'bicycle': {'cycling_speed': 13, 'shortest': True}}, 'id': 30}

**Comment by nilsnolde** [comment]
Yeah I’m pretty sure Mapbox is not exposing Valhalla directly anymore.. Why not the open server?

**Comment by atimpabi** [comment]
By open server, do you mean local host? I am sorry for my naive question. i
tried to look it up but its not really explaining much.

**Comment by atimpabi** [comment]
I really don't know what I'm doing without mapbox. I have watched some
videos and still cannot get around it. I tried to set up docker and the
check test indicated that it is not working. This feedback keep coming:

***@***.*** MINGW64 ~
$ docker run hello-world
docker: error during connect: this error may indicate that the docker
daemon is not running: Post
"http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/create":
open //./pipe/docker_engine: The system cannot find the file specified.
See 'docker run --help'.

**Comment by nilsnolde** [comment]
Sorry, forgot about this. I meant this one: https://valhalla1.openstreetmap.de/. That'll work. New version coming up now.
