### ISSUE TITLE
Hazardous material checkbox not transfer its value to request, width and length has strange conversion

### ISSUE THREAD

**Issue by radekvermirovsky** [gis-ops/valhalla-qgis-plugin#15]
If we route truck route with Weight for example 15 log showing using request with proper parameters:

<img width="1341" alt="image" src="https://github.com/gis-ops/valhalla-qgis-plugin/assets/149080356/00de21cc-4c56-4d66-a441-3f77afebb522">

if we check hazardous material checkbox, looks like its value is not properly converted, it is missing in request parameters so not taken in account, also other truck parameters are somehow converted. Valhalla standart input is in metric tons for weight and meters for width and length. But plugin converts 3 m width in input to 0,91 width in request and length 10 m in input to 3.05 in request.

So it looks like input for width and length is in feet (10 feet => 3,05m and 3 feet => 0,91 m) but Height is converted properly. I checked seetings of my qgis and looks like my default unit is meter but i dont even thing this is related.

<img width="1346" alt="image" src="https://github.com/gis-ops/valhalla-qgis-plugin/assets/149080356/62b605ff-3136-4fca-a7e1-d4b7a57117a6">

**Comment by nilsnolde** [comment]
hmpf yeah that rings a bell. there's some weird hack in there from way back when.

**Comment by radekvermirovsky** [comment]
Looks like for truck_length and truck_width this is converted by design in code...probably some compatibility with previous version of qgis (hardcoded division by 3.28084 and rounded to 2 decimal points) ...what is strange that this is not done for truck_height which is also in meters...but maybe height was added later and conversion was not needed at that time anymore
 
https://github.com/gis-ops/valhalla-qgis-plugin/blob/359f65a2ac897e66383d70c269c5bf2c06324dc3/valhalla/proc/request_builder.py#L105C16-L106C75

https://github.com/gis-ops/valhalla-qgis-plugin/blob/359f65a2ac897e66383d70c269c5bf2c06324dc3/valhalla/gui/common_gui.py#L80-l86

but didnt see for first look why hazmat is not builded in requeste params

**Comment by radekvermirovsky** [comment]
@nilsnolde i tested this after [https://github.com/gis-ops/valhalla-qgis-plugin/pull/18](url) was merged to master and both are fixed now. Dont now how this appears in public qgis plugin repe (probably needs to be published somehow there), but when i downloaded it localy it is fixed
