### ISSUE TITLE
Directions lines proc for truck is using pedestrian costing instead of truck costing

### ISSUE THREAD

**Issue by radekvermirovsky** [gis-ops/valhalla-qgis-plugin#16]
This python script
https://github.com/gis-ops/valhalla-qgis-plugin/blob/359f65a2ac897e66383d70c269c5bf2c06324dc3/valhalla/proc/directions_lines/directions_lines_truck.py

is using PedestrianCosting and IMO should use TruckCosting

https://github.com/gis-ops/valhalla-qgis-plugin/blob/359f65a2ac897e66383d70c269c5bf2c06324dc3/valhalla/proc/directions_lines/directions_lines_truck.py#L26

https://github.com/gis-ops/valhalla-qgis-plugin/blob/359f65a2ac897e66383d70c269c5bf2c06324dc3/valhalla/proc/directions_lines/directions_lines_truck.py#L36

**Comment by nilsnolde** [comment]
hehe yeah classic copy/paste fail

**Comment by radekvermirovsky** [comment]
Fixed in [https://github.com/gis-ops/valhalla-qgis-plugin/pull/18](url)
