### ISSUE TITLE
KeyError from 'sources_to_targets'

### ISSUE THREAD

**Issue by Ypsilonx** [gis-ops/valhalla-qgis-plugin#19]
Hello,
I'm having a problem with the results matrix at work.
It is 'sources_to_targets', when I enter the points and want to generate the results matrix I get a Python error instead of a table.

![image](https://github.com/gis-ops/valhalla-qgis-plugin/assets/109464813/74e4f794-1a0e-45ca-809c-176c2e2c1ba4)

Can I fix it?

**Comment by radekvermirovsky** [comment]
Experiencing same error.

**Comment by nilsnolde** [comment]
Likely coming from updating Valhalla on the FOSSGIS instance. I half remember this error, it's smth very trivial.

But also I seem to remember that everything actually works in the end. If you click OK and get rid of the error window, you do have the proper matrix layer right?

**Comment by radekvermirovsky** [comment]
@nilsnolde clicking ok doesnt help...no data displayed...python code error appears and no result...tested on FOGGIS instance and also on our own valhalla based on commercial data...same errorneous behavior.

**Comment by Ypsilonx** [comment]
I have result for this issue.
![image](https://github.com/gis-ops/valhalla-qgis-plugin/assets/109464813/bb42068f-8097-44b5-a7bf-0f6a048d9a38)

If I solve this trivial problem, the answer from FOSGIS is correct.
It creates a layer in the project with data for each route - only distance and time.

**Comment by Ypsilonx** [comment]
@nilsnolde i can push it to your code.

I have some next tasks (or upgrades) for this plugin.

Can i do it?

**Comment by nilsnolde** [comment]
Sure, would be appreciated!

**Comment by nilsnolde** [comment]
this is fixed since today. also threw in some other improvements, like:
- add time options for matrix
- optionally return geometries from the response
- be able to do many:many, 1:many and many:1 from the UI

probably also interesting for you @radekvermirovsky

**Comment by nilsnolde** [comment]
v2.5.0 was uploaded, but still needs to be approved: https://plugins.qgis.org/plugins/valhalla/version/2.5.0/

**Comment by radekvermirovsky** [comment]
@nilsnolde just tried this to investige something...amazing...really helpfull...thx

**Comment by nilsnolde** [comment]
Well I’m pretty sure it was the same thing as why I did the improvements;)
