### ISSUE TITLE
Valhalla pop-up window as a window

### ISSUE THREAD

**Issue by sanderpukk** [gis-ops/valhalla-qgis-plugin#3]
Hi!

Would it be possible to make the Valhalla pop-up as window?
Right now it disappears somewhere behind and is not ALT+TAB-able nor clickable from taskbar.
You have to find it behind stuff or click again from Web-> Valhalla.

**Comment by nilsnolde** [comment]
> pop-up as window

what is that? This is what it looks like on linux (no idea about other OSs):
![image](https://user-images.githubusercontent.com/25637358/106255945-f3917500-621a-11eb-9c44-734feff37dcc.png)

You do need to have the "Web" toolbar enabled. However, it's very possible that it's not working the same cross-platform, which would seriously suck (don't have the time checking all OSs).

What does it look like for you then?

**Comment by nilsnolde** [comment]
Also, on Linux, the window **always** stays on top of the main QGIS window. I thought about making it a dockable window, but then that would require the UI to change a lot as right now it can be really huge vertically if all dropdowns are un-collapsed.

**Comment by sanderpukk** [comment]
I looked over other plugins and native toolboxes. I kind of remembered falsely that they are a separated windows that can be alt+tab and clickable on taskbar.

My example is if you open the attribute table on some layer, it's a different entity that's opened.

**Comment by nilsnolde** [comment]
Ah right. Ok, that's not the case here, true. It's because attribute tables don't have a parent window, this plugin does (the main QGIS window). Bit of a style thing I guess. When you do the other approach, the plugin window disappears behind the main window when you click into the QGIS main window. And that annoys me to no end ;)

**Comment by sanderpukk** [comment]
Yeah, that's why I posted here :D I guess that's the native approach in QGIS. I usually only use QGIS for visualization and the actual work is done in PostGIS. I definitely admit my mistake :)
