### ISSUE TITLE
Only integer km values possible for isochrones?

### ISSUE THREAD

**Issue by magerlin** [gis-ops/valhalla-qgis-plugin#5]
Using the Processing module for isochrones it is impossible for me to specify isochrones distances in decimal kilometers like 0.5 and 1.5:

Traceback (most recent call last):
File "C:\Users/MAP/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\valhalla\proc\isochrones\isochrones_layer_auto.py", line 365, in processAlgorithm
"distance": [{"distance": int(x)} for x in intervals_distance.split(',')] if intervals_distance else []
File "C:\Users/MAP/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\valhalla\proc\isochrones\isochrones_layer_auto.py", line 365, in <listcomp>
"distance": [{"distance": int(x)} for x in intervals_distance.split(',')] if intervals_distance else []
ValueError: invalid literal for int() with base 10: '0.5'

Execution failed after 0.01 seconds

Decimal kilometres are relevant when working with pedestrians....

**Comment by nilsnolde** [comment]
We’re actually about to deprecate this (was a bit polished debugging tool for our Valhalla dev), as a much better plugin is coming soonish. 

we might fix this and re-publish. Or you just fix it in your local plugin code?

**Comment by magerlin** [comment]
Hi Nils

Even though my Python knowledge is limited I actually have considered trying to fix it myself. Guess it should be quite simple. Will look at it.

And as a transportplanner I will look forward for the new polished version 😊

Have a nice weekend!

Best regards/Med venlig hilsen

Morten Agerlin Petersen
________________________________

**Comment by nilsnolde** [comment]
Ha great, you can definitely be one of our beta testers if you want! Our end goal will be similar as ESRI's network analyst and will contain location/allocation/optimization/isochrones and a street view (all roads as geometries reachable within a certain time, very similar to isochrones) and you won't have to have a API anymore, it'll all run locally with valhalla & osrm. we're actually really excited to release that, but might take until the end of the year before we have a beta to distribute around.

as for the python: just replace the `int` with `float` and it'll work:)

**Comment by magerlin** [comment]
Hi Nils

I have managed to make Valhalla calculate isochrones using floating intervals by changing INT to FLOAT in isochrones_layer_auto.py:

***@***.***

I also changed it in isochrones_core.py but I do not think that actually was necessary or did any change:

***@***.***


The resulting polygons are now correctly calculated and drawn using the floating values even though they still are labelled and categorized using int values but I can live with that for now.

If you are reusing some of the code I will point at one general error in the Isochrone results: Resulting polygons for both time and distance are labelled “mins”:

When I ask for:
***@***.***

I get these polygons:
***@***.***


As a descendant of the Danish Vikings I will enjoy to help making Valhalla great 😊 and participate in beta testing!

Kind regards
Morten Agerlin Petersen
Senior Transport Planner, GIS and Data Analysis Specialist
M +45 51613615
***@***.******@***.***>
Rambøll Danmark A/S, CVR NR. 35128417
Hjemsted: Hannemanns Allé 53, 2300 København S
